import { Check, Search, X } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { memberManagementApi, type DepositRequestItem } from '../../../api/memberManagement';
import { useAdminPageRefresh } from '../../../hooks/useAdminPageRefresh';
import { MemberPageHeader } from '../MemberManagementNav';

export function DepositRequestPage(){const [items,setItems]=useState<DepositRequestItem[]>([]);const [selected,setSelected]=useState<DepositRequestItem|null>(null);const [query,setQuery]=useState('');const [filter,setFilter]=useState('PENDING');const [memo,setMemo]=useState('');const [message,setMessage]=useState('');const [processing,setProcessing]=useState(false);
  const load=useCallback(async()=>{setMessage('');try{const data=await memberManagementApi.depositRequests();setItems(data);setSelected((current)=>data.find((item)=>item.id===current?.id)??data.find((item)=>item.status==='PENDING')??data[0]??null);}catch(e){setMessage(errorOf(e));}},[]);useEffect(()=>{void load();},[load]);useAdminPageRefresh(load);
  useEffect(()=>{setMemo(selected?.adminMemo??'');},[selected]);
  const filtered=useMemo(()=>items.filter((item)=>(filter==='ALL'||item.status===filter)&&`${item.memberName} ${item.loginId} ${item.depositorName}`.toLowerCase().includes(query.toLowerCase())),[items,query,filter]);
  async function process(action:'approve'|'reject'){if(!selected||selected.status!=='PENDING')return;setProcessing(true);setMessage('');try{const updated=action==='approve'?await memberManagementApi.approveDeposit(selected.id,memo):await memberManagementApi.rejectDeposit(selected.id,memo);setItems((all)=>all.map((item)=>item.id===updated.id?updated:item));setSelected(updated);setMessage(action==='approve'?'예치금 신청을 승인했습니다.':'예치금 신청을 반려했습니다.');}catch(e){setMessage(errorOf(e));}finally{setProcessing(false);}}
  return <section className="admin-page"><MemberPageHeader title="예치금신청" description="회원의 입금 신청을 확인한 뒤 승인하거나 반려합니다."/><div className="member-toolbar"><label className="admin-search-box"><Search size={17}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="회원 또는 입금자명 검색"/></label><select value={filter} onChange={(e)=>setFilter(e.target.value)}><option value="ALL">전체 상태</option><option value="PENDING">처리 대기</option><option value="APPROVED">승인</option><option value="REJECTED">반려</option></select></div>
    <div className="member-request-layout"><div className="member-table-panel"><table className="member-data-table"><thead><tr><th>신청일</th><th>회원</th><th>입금자명</th><th>신청금액</th><th>상태</th></tr></thead><tbody>{filtered.map((item)=><tr key={item.id} className={selected?.id===item.id?'is-selected':''} onClick={()=>setSelected(item)}><td>{dateTime(item.requestedAt)}</td><td><strong>{item.memberName}</strong><small>{item.loginId}</small></td><td>{item.depositorName}</td><td>{item.amount.toLocaleString()}원</td><td><span className={`member-status ${item.status.toLowerCase()}`}>{status(item.status)}</span></td></tr>)}{filtered.length===0&&<tr><td colSpan={5} className="member-empty">예치금 신청이 없습니다.</td></tr>}</tbody></table></div>
      <aside className="member-request-detail">{selected?<><div className="member-panel-title"><h2>신청 상세</h2><span className={`member-status ${selected.status.toLowerCase()}`}>{status(selected.status)}</span></div><dl><div><dt>회원</dt><dd>{selected.memberName} ({selected.loginId})</dd></div><div><dt>입금자명</dt><dd>{selected.depositorName}</dd></div><div><dt>신청금액</dt><dd>{selected.amount.toLocaleString()}원</dd></div><div><dt>신청일</dt><dd>{dateTime(selected.requestedAt)}</dd></div><div><dt>처리일</dt><dd>{selected.processedAt?dateTime(selected.processedAt):'-'}</dd></div></dl><label>관리자 메모<textarea rows={5} value={memo} onChange={(e)=>setMemo(e.target.value)} disabled={selected.status!=='PENDING'}/></label>{selected.status==='PENDING'&&<div className="member-request-actions"><button className="member-reject-button" onClick={()=>void process('reject')} disabled={processing}><X size={16}/>반려</button><button className="member-primary-button" onClick={()=>void process('approve')} disabled={processing}><Check size={16}/>승인</button></div>}</>:<p className="member-empty">신청을 선택하세요.</p>}{message&&<p className="member-message">{message}</p>}</aside>
    </div></section>;
}
function status(value:string){return value==='PENDING'?'처리 대기':value==='APPROVED'?'승인':'반려';}function dateTime(value:string){return new Date(value).toLocaleString('ko-KR');}function errorOf(e:unknown){return e instanceof Error?e.message:'요청을 처리하지 못했습니다.';}
