spring:
  application:
    name: shop
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:dy486251379}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

shop:
  upload:
    inquiry-image-dir: ${SHOP_INQUIRY_IMAGE_DIR:uploads/inquiries_images}
