const API_BASE_URL=import.meta.env.VITE_API_BASE_URL??'';
type ApiErrorBody={message?:string;detail?:string;messages?:string[]}|null;
export type SettingEntry={id:number;type:string;code:string;name:string;content:string|null;fields:Record<string,string>;displayOrder:number;active:boolean;createdAt:string;updatedAt:string};
export type SettingPayload=Omit<SettingEntry,'id'|'type'|'createdAt'|'updatedAt'>;
export type AdminItem={id:number;loginId:string;name:string;active:boolean;createdAt:string};
export type AdminPayload={loginId:string;name:string;password:string;active:boolean};
export type CurrentAdmin={adminId:number;loginId:string;name:string};
export type MailTemplateType='SIGNUP'|'MARKETING'|'NOTICE'|'CUSTOM';
export type MailTemplate={id:number;code:string;name:string;templateType:MailTemplateType;subject:string;senderName:string;replyTo:string;content:string;defaultTemplate:boolean;displayOrder:number;active:boolean;createdAt:string;updatedAt:string};
export type MailTemplatePayload=Omit<MailTemplate,'id'|'createdAt'|'updatedAt'>;
export type MailDeliveryStatus={enabled:boolean;configured:boolean;message:string};
export type MailProvider='NAVER'|'GMAIL'|'CUSTOM';
export type MailAddress={id:number;provider:MailProvider;host:string;port:number;username:string;senderName:string;passwordConfigured:boolean;active:boolean;updatedAt:string};
export type MailAddressPayload={provider:MailProvider;host:string;port:number;username:string;password:string;senderName:string;active:boolean};
export function settingsEntryApi(endpoint:string){const base=`/api/admin/settings-management/${endpoint}`;return{findAll:()=>request<SettingEntry[]>(base),create:(p:SettingPayload)=>request<SettingEntry>(base,json('POST',p)),update:(id:number,p:SettingPayload)=>request<SettingEntry>(`${base}/${id}`,json('PUT',p)),delete:(id:number)=>request<void>(`${base}/${id}`,{method:'DELETE'})};}
export const adminSettingsApi={findAll:()=>request<AdminItem[]>('/api/admin/settings-management/admins'),current:()=>request<CurrentAdmin>('/api/admin/auth/me'),create:(p:AdminPayload)=>request<AdminItem>('/api/admin/settings-management/admins',json('POST',p)),update:(id:number,p:AdminPayload)=>request<AdminItem>(`/api/admin/settings-management/admins/${id}`,json('PUT',p)),delete:(id:number)=>request<void>(`/api/admin/settings-management/admins/${id}`,{method:'DELETE'})};
export const mailTemplateApi={findAll:()=>request<MailTemplate[]>('/api/admin/settings-management/mail-templates'),deliveryStatus:()=>request<MailDeliveryStatus>('/api/admin/settings-management/mail-templates/delivery-status'),create:(p:MailTemplatePayload)=>request<MailTemplate>('/api/admin/settings-management/mail-templates',json('POST',p)),update:(id:number,p:MailTemplatePayload)=>request<MailTemplate>(`/api/admin/settings-management/mail-templates/${id}`,json('PUT',p)),delete:(id:number)=>request<void>(`/api/admin/settings-management/mail-templates/${id}`,{method:'DELETE'}),sendTest:(id:number,recipient:string)=>request<void>(`/api/admin/settings-management/mail-templates/${id}/test`,json('POST',{recipient}))};
export const mailAddressApi={find:()=>request<MailAddress|undefined>('/api/admin/settings-management/mail-address'),status:()=>request<MailDeliveryStatus>('/api/admin/settings-management/mail-address/status'),save:(p:MailAddressPayload)=>request<MailAddress>('/api/admin/settings-management/mail-address',json('PUT',p)),test:(recipient:string)=>request<void>('/api/admin/settings-management/mail-address/test',json('POST',{recipient}))};
function json(method:string,body:unknown):RequestInit{return{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);try{if(init.method&&!['GET','HEAD'].includes(init.method.toUpperCase())){const csrf=await fetch(`${API_BASE_URL}/api/admin/auth/csrf`,{credentials:'include'});if(!csrf.ok)throw new Error('보안 토큰을 발급받지 못했습니다.');const token=await csrf.json() as {headerName:string;token:string};headers.set(token.headerName,token.token);}const response=await fetch(`${API_BASE_URL}${path}`,{...init,headers,credentials:'include'});if(response.status===401)window.dispatchEvent(new Event('admin-auth-expired'));if(!response.ok){const text=await response.text();let body:ApiErrorBody=null;try{body=JSON.parse(text) as ApiErrorBody}catch{body=null}const fallback=response.status>=500?'백엔드 서버에 연결하지 못했거나 서버 처리 중 오류가 발생했습니다. 백엔드 실행 상태를 확인해주세요.':'요청을 처리하지 못했습니다.';throw new Error(body?.message??body?.detail??body?.messages?.[0]??fallback);}if(response.status===204)return undefined as T;return response.json() as Promise<T>;}catch(error){if(error instanceof TypeError)throw new Error('백엔드 서버에 연결할 수 없습니다. 백엔드를 실행한 뒤 다시 시도해주세요.');throw error;}}
