import { Eye,EyeOff,Plus,Save,Search,Trash2 } from 'lucide-react';import { useCallback,useEffect,useRef,useState } from 'react';import { settingsEntryApi,type SettingEntry,type SettingPayload } from '../../api/settingsManagement';import { useAdminPageRefresh } from '../../hooks/useAdminPageRefresh';import { loadKoreanPostcode,openKoreanPostcode } from '../../utils/koreanPostcode';import { SettingsPageHeader } from './SettingsManagementNav';
export type SettingField={key:string;label:string;type?:'text'|'number'|'textarea'|'select'|'email'|'tel';placeholder?:string;options?:Array<[string,string]>;required?:boolean;min?:number;max?:number};
export type SettingPageConfig={endpoint:string;title:string;description:string;itemName:string;codeLabel:string;nameLabel:string;contentLabel?:string;contentRequired?:boolean;koreanAddress?:boolean;fields:SettingField[];singleton?:boolean};
const empty=(fields:SettingField[]):SettingPayload=>({code:'',name:'',content:'',fields:Object.fromEntries(fields.map(x=>[x.key,''])),displayOrder:1,active:true});
export function SettingsEntryPage({config}:{config:SettingPageConfig}){const api=settingsEntryApi(config.endpoint);const [items,setItems]=useState<SettingEntry[]>([]);const [selectedId,setSelectedId]=useState<number|null>(null);const [form,setForm]=useState<SettingPayload>(()=>empty(config.fields));const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
 const select=(item:SettingEntry)=>{setSelectedId(item.id);setForm({code:item.code,name:item.name,content:item.content??'',fields:{...item.fields},displayOrder:item.displayOrder,active:item.active});setMessage('')};
 const load=useCallback(async()=>{try{const data=await api.findAll();setItems(data);const first=data.find(x=>x.id===selectedId)??data[0];if(first)select(first);else{setSelectedId(null);setForm(empty(config.fields));}}catch(e){setMessage(errorText(e));}},[config.endpoint]);useEffect(()=>{void load();},[load]);useAdminPageRefresh(load);
 const createNew=()=>{setSelectedId(null);setForm({...empty(config.fields),displayOrder:items.length+1});setMessage('')};
 async function save(){const validationMessage=validate(config,form);if(validationMessage)return setMessage(validationMessage);setSaving(true);setMessage('');try{const saved=selectedId?await api.update(selectedId,form):await api.create(form);const next=selectedId?items.map(x=>x.id===saved.id?saved:x):[...items,saved];setItems(next);select(saved);setMessage(`${config.itemName}을 저장했습니다.`);}catch(e){setMessage(errorText(e));}finally{setSaving(false)}}
 async function remove(){if(!selectedId||!confirm(`${config.itemName}을 삭제할까요?`))return;try{await api.delete(selectedId);const next=items.filter(x=>x.id!==selectedId);setItems(next);if(next[0])select(next[0]);else createNew();}catch(e){setMessage(errorText(e));}}
 return <section className="admin-page"><SettingsPageHeader title={config.title} description={config.description}/><div className={`settings-content-layout${config.singleton?' singleton':''}`}>
  {!config.singleton&&<aside className="settings-list"><div className="settings-list-head"><strong>{config.itemName} 목록</strong><button onClick={createNew} title={`${config.itemName} 추가`}><Plus size={17}/></button></div>{items.map(item=><button key={item.id} className={selectedId===item.id?'active':''} onClick={()=>select(item)}><span>{item.active?<Eye size={13}/>:<EyeOff size={13}/>} 순서 {item.displayOrder}</span><strong>{item.name}</strong><small>{item.code}</small></button>)}{items.length===0&&<p>등록된 항목이 없습니다.</p>}</aside>}
  <div className="settings-editor"><div className="settings-form-grid"><label>{config.codeLabel}<input value={form.code} disabled={Boolean(config.singleton&&selectedId)} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>{config.nameLabel}<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label></div>
   {config.koreanAddress&&<KoreanAddressField fields={form.fields} onChange={fields=>setForm({...form,fields})} onMessage={setMessage}/>}
   {config.fields.filter(field=>!config.koreanAddress||!['postalCode','address1','address2'].includes(field.key)).map(field=><Field key={field.key} field={field} value={form.fields[field.key]??''} onChange={value=>setForm({...form,fields:{...form.fields,[field.key]:value}})}/>)}
   {config.contentLabel&&<div className="settings-content-field"><strong>{config.contentLabel}</strong><textarea aria-label={config.contentLabel} rows={14} value={form.content??''} onChange={e=>setForm({...form,content:e.target.value})}/></div>}
   {!config.singleton&&<label>노출 순서<input type="number" min="0" value={form.displayOrder} onChange={e=>setForm({...form,displayOrder:Number(e.target.value)})}/></label>}
   <div className="settings-editor-footer"><label className="settings-active"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> 사용</label><div>{selectedId&&!config.singleton&&<button className="admin-danger-button" onClick={remove}><Trash2 size={16}/>삭제</button>}<button className="admin-blue-outline-button" onClick={save} disabled={saving}><Save size={16}/>{saving?'저장 중':'저장'}</button></div></div>{message&&<p className="board-message">{message}</p>}
  </div></div></section>}
function Field({field,value,onChange}:{field:SettingField;value:string;onChange:(v:string)=>void}){return <label>{field.label}{field.type==='textarea'?<textarea rows={5} value={value} required={field.required} placeholder={field.placeholder} onChange={e=>onChange(e.target.value)}/>:field.type==='select'?<select required={field.required} value={value} onChange={e=>onChange(e.target.value)}><option value="" disabled hidden>{field.placeholder??'선택하세요'}</option>{field.options?.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input type={field.type??'text'} value={value} required={field.required} min={field.min} max={field.max} placeholder={field.placeholder} onChange={e=>onChange(e.target.value)}/>}</label>}
function KoreanAddressField({fields,onChange,onMessage}:{fields:Record<string,string>;onChange:(fields:Record<string,string>)=>void;onMessage:(message:string)=>void}){const detailRef=useRef<HTMLInputElement>(null);useEffect(()=>{void loadKoreanPostcode().catch(()=>undefined)},[]);async function search(){onMessage('');try{await openKoreanPostcode(result=>{onChange({...fields,postalCode:result.postalCode,address1:result.baseAddress,address2:''});requestAnimationFrame(()=>detailRef.current?.focus())})}catch(e){onMessage(errorText(e))}}return <div className="settings-address-fields"><strong>국내 배송지 주소</strong><div className="settings-postcode-row"><label>우편번호<input value={fields.postalCode??''} readOnly placeholder="우편번호 찾기를 이용해주세요"/></label><button type="button" className="admin-blue-outline-button" onClick={()=>void search()}><Search size={16}/>우편번호 찾기</button></div><label>기본 주소<input value={fields.address1??''} readOnly placeholder="도로명, 건물명 또는 지번으로 검색해주세요"/></label><label>상세 주소<input ref={detailRef} value={fields.address2??''} placeholder="동·호수 등 상세주소를 입력해주세요" onChange={e=>onChange({...fields,address2:e.target.value})}/></label></div>}
function errorText(e:unknown){return e instanceof Error?e.message:'요청을 처리하지 못했습니다.'}
function validate(config:SettingPageConfig,form:SettingPayload){if(!form.code.trim())return `${config.codeLabel}을(를) 입력해주세요.`;if(!form.name.trim())return `${config.nameLabel}을(를) 입력해주세요.`;if(config.contentRequired&&!(form.content??'').trim())return `${config.contentLabel??'내용'}을(를) 입력해주세요.`;for(const field of config.fields){const value=(form.fields[field.key]??'').trim();if(field.required&&!value)return `${field.label}을(를) 입력해주세요.`;if(!value)continue;if(field.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))return `${field.label} 형식이 올바르지 않습니다.`;if(field.type==='tel'&&!/^[0-9+()\-\s]{8,20}$/.test(value))return `${field.label} 형식이 올바르지 않습니다.`;if(field.type==='number'){const number=Number(value);if(!Number.isFinite(number))return `${field.label}에는 숫자만 입력해주세요.`;if(field.min!==undefined&&number<field.min)return `${field.label}은(는) ${field.min} 이상이어야 합니다.`;if(field.max!==undefined&&number>field.max)return `${field.label}은(는) ${field.max} 이하여야 합니다.`;}}return ''}
